Fix string ledger_index
XRPLF/clio pull request #1019
Opened 2023-12-05 14:23 UTC by cindyyan317

When api_version is 2, ledger_index should be always int.
Fix #1014

2023-12-07 19:58 UTC, godexsoft requested changes
Looks good, just a few small comments regarding formatting and types 👍

2023-12-07 19:58 UTC, godexsoft commented on src/rpc/RPCHelpers.cpp
> +        if (apiVersion < 2) {
Let's use `2u` so we don't get a warning

2023-12-07 19:58 UTC, godexsoft commented on unittests/rpc/RPCHelpersTests.cpp
> +    auto const binJson = toJson(ledgerHeader, true, 1);
Consider using `1u` here and in other places below where `toJson` is used

2023-12-07 19:58 UTC, godexsoft commented on unittests/rpc/handlers/LedgerDataTests.cpp
> +        //"close_time_human" 's format depends on platform, might be sightly different
Please add some space before the comment line and let's use spaces and capitalisation to make it more readable. Something like this:

// Note: the format of "close_time_human" depends on the platform and might differ per platform. It is however guaranteed to be consistent on the same platform.

2023-12-07 19:58 UTC, godexsoft commented on src/rpc/RPCHelpers.cpp
> +        if (apiVersion < 2) {
I'd also maybe move this if/else block to the bottom and have a space between the block and the rest of the code.

2023-12-08 13:45 UTC, kuznetsss approved these changes
LGTM

2023-12-08 13:57 UTC, godexsoft approved these changes
LGTM!

2023-12-08 14:20 UTC, merged