Create generate free port class to avoid conflicting ports
XRPLF/clio pull request #1439
Opened 2024-05-30 19:44 UTC by PeterChen13579

Fixes #1317

2024-05-31 10:12 UTC, kuznetsss commented
There are also `tests/unit/web/ServerTests.cpp`, `tests/unit/etl/SubscriptionSourceTests.cpp` and `tests/unit/rpc/ForwardingProxyTests.cpp` where we should use random port.

2024-05-31 16:46 UTC, godexsoft commented on tests/common/util/AssignRandomPort.cpp
> +    Copyright (c) 2023, the clio developers.
2024

2024-05-31 16:46 UTC, godexsoft commented on tests/common/util/AssignRandomPort.hpp
> +    Copyright (c) 2023, the clio developers.
also 2024

2024-05-31 16:49 UTC, godexsoft commented on tests/common/util/AssignRandomPort.cpp
> +    tcp::endpoint endPoint = acceptor.local_endpoint();
nit: The names look a bit strange. `endpoint` and then `endPoint`. Consider renaming to something like `localEndpoint` or perhaps we don't even need the temporary there.

2024-05-31 16:50 UTC, godexsoft commented on tests/common/util/AssignRandomPort.hpp
> +using tcp = boost::asio::ip::tcp;
This is always a no-no. Never add using in header files, only in cpp files 👍

2024-05-31 16:51 UTC, godexsoft commented on tests/common/util/MockXrpLedgerAPIService.hpp
> +    getXRPLMockPort()
This probably should be `const`-qualified.

2024-05-31 16:52 UTC, godexsoft commented on tests/common/util/MockXrpLedgerAPIService.hpp
> +    int port_;
Is this the correct type?

2024-05-31 16:53 UTC, godexsoft requested changes
Leaving a few comments and suggestions 👍

2024-06-04 14:14 UTC, kuznetsss commented on tests/common/util/AssignRandomPort.cpp
> +    return localEndPoint.port();
Minor thing, you could do
```cpp
return acceptor.local_endpoint().port();
```

2024-06-04 14:14 UTC, kuznetsss commented on tests/unit/etl/SubscriptionSourceTests.cpp
> +    TestWsServer wsServer_{ioContext_, "0.0.0.0", port};
I think instead it is better to remove port parameter from `TestWsServer`'s constructor and use always `0`.  Then add `port()` method for `TestWsServer` and use it below.

2024-06-04 14:14 UTC, kuznetsss commented on tests/unit/util/requests/RequestBuilderTests.cpp
> +    RequestBuilder builder{"localhost", std::to_string(port)};
And the same as for `TestWsServer` here.

2024-06-04 14:25 UTC, kuznetsss commented on tests/unit/web/ServerTests.cpp
> +    uint32_t port = tests::util::generateFreePort();
Probably better to save it as `std::string`

2024-06-05 10:54 UTC, kuznetsss commented on tests/common/util/TestHttpServer.cpp
> +TestHttpServer::port() const
You also should remove `port` parameter form constructor for `TestHttpServer` and `TestWsServer` and use `0` instead.

2024-06-05 16:56 UTC, kuznetsss approved these changes, later dismissed
👍

2024-06-10 13:59 UTC, godexsoft requested changes
Looks good, just fix the doxy comment and let's ship it 🚀

2024-06-10 13:59 UTC, godexsoft commented on tests/common/util/TestHttpServer.hpp
>       * @param port port to bind to
This will later trigger doxygen to error out.. best removed now since the param is already gone 👍

2024-06-17 01:46 UTC, godexsoft submitted a review, later dismissed

2024-06-18 10:29 UTC, kuznetsss approved these changes

2024-06-18 10:29 UTC, merged