cache commands that dont take parameters
XRPLF/clio pull request #153
Opened 2022-05-11 16:47 UTC by natenichols

2022-05-25 17:43 UTC, cjcobb23 commented on CMake/settings.cmake
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing -Wall -Werror -Wno-error=deprecated-declarations -Wno-dangling-else")
remove

2022-06-06 16:41 UTC, cjcobb23 requested changes

2022-06-06 16:41 UTC, cjcobb23 commented on src/etl/ETLSource.h
> +        timer_.expires_after(boost::asio::chrono::seconds(duration_));
Change this to milliseconds

2022-06-06 16:41 UTC, cjcobb23 commented on src/etl/ETLSource.h
> +    std::uint32_t duration_ = 10;
I think we should default to every 100ms

2022-06-06 16:41 UTC, cjcobb23 commented on src/etl/ETLSource.h
> +        timer_.async_wait([this](auto const& ec) { freshen(ec); });
I'm wondering if instead of doing this on a timer, we do this every time we receive a proposed transaction

2022-06-06 19:41 UTC, natenichols commented on src/etl/ETLSource.h
> +        timer_.async_wait([this](auto const& ec) { freshen(ec); });
We can freshen after we hear `ledgerClosed` or something like that, but I think that this will run too often if run on every `transaction_proposed`...

2022-06-06 19:41 UTC, natenichols commented on src/etl/ETLSource.h
> +        timer_.async_wait([this](auto const& ec) { freshen(ec); });
Or we can also do something like every `n` messages...

2022-06-06 20:20 UTC, natenichols commented on src/etl/ETLSource.h
> +    std::uint32_t duration_ = 10;
That seems a little too often

2022-06-15 20:30 UTC, cjcobb23 approved these changes
LGTM

2022-06-15 21:18 UTC, merged