Fix nftData unique bug
XRPLF/clio pull request #1550
Opened 2024-07-23 11:07 UTC by cindyyan317

Similar with this one. https://github.com/XRPLF/clio/pull/1542 
It failed to unique the NFT data as we wish.

It will write incorrect data if 
1 mint and burn happen in the same ledger , wrong data write to nf_tokens and uri tables.
2 accept nft offer and burn happen in the same ledger, the isburn maybe incorrect.

2024-07-23 17:50 UTC, shawnxie999 commented
> 1 mint and burn happen in the same ledger , wrong data write to nf_tokens and uri tables.
IMO it should not matter. A NFT that was minted and burned in the ledger could be regarded as "non-existent".

> 2 accept nft offer and burn happen in the same ledger, the isburn maybe incorrect.
How would it be incorrect? the data from the burn will have the correct owner and isBurn.

2024-07-24 10:43 UTC, cindyyan317 commented
> How would it be incorrect? the data from the burn will have the correct owner and isBurn.

As the test code shows,  https://godbolt.org/z/jP384P7rb, the sorted result is not what we expected. 
The 1:1 is sorted after 1:2 sometimes.  So the burn tx actually can get erased, so only the nftDatas from accept offer tx gets stored in DB. 

>IMO it should not matter. A NFT that was minted and burned in the ledger could be regarded as "non-existent".

Again, the sorted result is not expected. So the nftDatas from burn tx might get removed. 

I agreed the token minted and burned in the same ledger should be considered as "non-existent", however, current implementation will save the data into the DB , right? Maybe this is another bug we shall fix.

2024-07-24 11:02 UTC, kuznetsss commented on src/etl/NFTHelpers.cpp
> +getUniqueNFTsDatas(std::vector<NFTsData> const& nfts)
Probably there is no point to pass it as const reference since you copy it anyway.

2024-07-24 11:09 UTC, kuznetsss approved these changes, later dismissed
Looks good, just a few nits, but feel free to ignore.

2024-07-24 11:09 UTC, kuznetsss commented on src/etl/NFTHelpers.cpp
> +    std::sort(results.begin(), results.end(), [](NFTsData const& a, NFTsData const& b) {
`std::ranges::sort` would look a bit nicer.

2024-07-24 11:54 UTC, godexsoft requested changes
Few small things on top of what others already noticed 👍

2024-07-24 11:54 UTC, godexsoft commented on src/etl/NFTHelpers.hpp
> +
Something went wrong with the format here

2024-07-24 11:54 UTC, godexsoft commented on src/etl/NFTHelpers.cpp
> +    // Remove all but the last NFTsData for each id. unique removes all but the first of a group, so we want to
This could be a doxygen note instead perhaps? I mean, the code speaks for itself tbh

2024-07-24 11:54 UTC, godexsoft commented on src/etl/NFTHelpers.cpp
> +    // Remove all but the last NFTsData for each id. unique removes all but the first of a group, so we want to
At the very least, it needs a line of space before the comment here or move the comment all the way up

2024-07-24 12:02 UTC, cindyyan317 commented on src/etl/NFTHelpers.cpp
> +getUniqueNFTsDatas(std::vector<NFTsData> const& nfts)
I think we can keep it. Just in case, if it is modified in function, we can get error from compiler.

2024-07-24 13:23 UTC, kuznetsss commented on src/etl/NFTHelpers.cpp
> +    std::ranges::sort(finalIDs.begin(), finalIDs.end());
I thought for ranges you could do 
```cpp
std::ranges::sort(finalIDs);
```

2024-07-24 13:29 UTC, kuznetsss commented on src/etl/NFTHelpers.cpp
> +    std::ranges::sort(txs.begin(), txs.end(), [](NFTTransactionsData const& a, NFTTransactionsData const& b) {
Also here and below begin and end could be avoided.

2024-07-24 13:34 UTC, kuznetsss approved these changes
👍

2024-07-24 14:34 UTC, shawnxie999 approved these changes
Looks good. Thanks for fixing this! 🙇

2024-07-25 09:22 UTC, kuznetsss approved these changes

2024-07-25 10:03 UTC, godexsoft approved these changes

2024-07-25 10:05 UTC, merged