fix: Check ledger range in every handler
XRPLF/clio pull request #1755
Opened 2024-11-25 17:13 UTC by PeterChen13579

fixes #1565

2024-11-26 12:06 UTC, kuznetsss commented on tests/unit/rpc/handlers/AllHandlerTests.cpp
> +            return HandlerType{this->backend, this->mockAmendmentCenterPtr};
Don't you need to initialise `mockAmendmentCenterPtr` before providing it into the handler here? Looks like it is `nullptr` now, but maybe I'm wrong.

2024-11-26 12:06 UTC, kuznetsss commented on tests/unit/rpc/handlers/AllHandlerTests.cpp
> +            EXPECT_DEATH({ [[maybe_unused]] auto _unused = handler.process(input, context); }, ".*");
Maybe you could add a pattern `Assertion .* failed.*`.

2024-11-26 17:53 UTC, kuznetsss commented on tests/unit/rpc/handlers/AllHandlerTests.cpp
> +    StrictMockAmendmentCenterSharedPtr mockAmendmentCenterPtr;
Maybe you could add an ASSERT in `initHandler()` to prevent the error in the future.

2024-11-27 11:07 UTC, cindyyan317 requested changes
It's not **every handler.** I did not see `subscribe`  `unsubscribe`, they are immune?

2024-11-29 11:00 UTC, cindyyan317 approved these changes

2024-11-29 15:11 UTC, merged