feat: Graceful shutdown
XRPLF/clio pull request #1801
Opened 2024-12-20 17:11 UTC by kuznetsss

For #442. This is a WIP PR containing current state of graceful shutdown.

2024-12-23 14:15 UTC, godexsoft requested changes
Adding some small suggestions. Looks pretty good 👍

2024-12-23 14:15 UTC, godexsoft commented on src/app/Stopper.hpp
> +    std::thread worker_;
Should we use async framework here or is this deliberately not using it?

2024-12-23 14:15 UTC, godexsoft commented on src/etl/impl/SubscriptionSource.cpp
> +        }
```suggestion
        if (auto connection = wsConnectionBuilder_.connect(yield); connection) {
            wsConnection_ = std::move(connection).value();
        } else {
            handleError(connection.error(), yield);
            return;
        }
```

This scopes `connection` so that there is no way anyone can use it after we moved from it, even if they wanted to

2024-12-23 14:15 UTC, godexsoft commented on src/etl/impl/SubscriptionSource.cpp
> +        auto const writeErrorOpt = wsConnection_->write(subscribeCommand, yield, wsTimeout_);
Same as above

2024-12-23 14:15 UTC, godexsoft commented on src/etl/impl/SubscriptionSource.cpp
>              }
And more of the same 👍

2024-12-23 14:15 UTC, godexsoft commented on src/util/StopHelper.cpp
> +    if (not*stopped_)
Maybe in this case `!*stopped_` is better? 😃

2024-12-23 14:15 UTC, godexsoft commented on src/util/StopHelper.cpp
> +    boost::system::error_code error;
Should we do anything at all about this error if it's set?

2024-12-23 14:15 UTC, godexsoft commented on src/web/ng/Server.cpp
> +            [connection = std::move(connectionExpected).value()](boost::asio::yield_context yield) {
nit: Here and other places - we usually pass `yield` as `auto` in lambdas

2024-12-23 14:15 UTC, godexsoft commented on src/app/ClioApplication.cpp
> +            // etl->stop();
Are these left intentionally for future or just forgotten to be removed?

2025-01-06 16:34 UTC, kuznetsss commented on src/app/Stopper.hpp
> +    std::thread worker_;
Hm, I don't need context switching or stop token here, but probably still could switch.

2025-01-06 16:38 UTC, kuznetsss commented on src/etl/impl/SubscriptionSource.cpp
> +        }
It is an old code, but I will update 👍

2025-01-06 16:43 UTC, kuznetsss commented on src/util/StopHelper.cpp
> +    boost::system::error_code error;
The error will be something like `operation_aborted` when timer is cancelled. If we don't provide an error, exception will be thrown when timer is cancelled.

2025-01-06 16:44 UTC, kuznetsss commented on src/app/ClioApplication.cpp
> +            // etl->stop();
It is still draft, so it will be fixed later.

2025-01-06 16:47 UTC, kuznetsss commented on src/web/ng/Server.cpp
> +            [connection = std::move(connectionExpected).value()](boost::asio::yield_context yield) {
Why? Clangd couldn't guess the type here when `yield` is `auto`, but I understand that more typing is also not very convenient.

2025-01-06 17:43 UTC, godexsoft commented on src/web/ng/Server.cpp
> +            [connection = std::move(connectionExpected).value()](boost::asio::yield_context yield) {
No particular reason other than the usual preference towards using `auto` when possible. 
Without `auto` there is indeed more typing as well as the need to include the header that provides the type of `yield` (because we enforce `iwyu`).

2025-01-07 12:25 UTC, kuznetsss commented on src/app/Stopper.hpp
> +    std::thread worker_;
I tried but it seems async framework doesn't fit here because it doesn't allow to create a background task without saving a task token somewhere.

2025-01-09 18:06 UTC, kuznetsss commented on src/web/ng/Server.cpp
> +    connectionHandler_.stop(yield);
This should be covered by test.

2025-01-22 10:12 UTC, cindyyan317 commented on src/app/Stopper.hpp
> +    Copyright (c) 2024, the clio developers.
2025

2025-01-22 10:29 UTC, cindyyan317 reviewed
Do we need to consider that shutdown happens during cache loading?

2025-01-22 11:45 UTC, kuznetsss commented on src/app/Stopper.hpp
> +    Copyright (c) 2024, the clio developers.
I created it in 2024 😄

2025-01-22 13:07 UTC, cindyyan317 approved these changes
LGTM

2025-01-22 13:09 UTC, merged