Fmendoz7#223
XRPLF/clio pull request #324
Opened 2022-09-24 03:43 UTC by officialfrancismendoza

Change to noripple_check to include the limit range

2022-09-26 14:57 UTC, godexsoft requested changes

2022-09-26 14:57 UTC, godexsoft commented on CONTRIBUTING.md
> +* [officialfrancismendoza](https://github.com/officialfrancismendoza) (Ripple)
Not sure how this change got into this pr but it should not be (it was in #285 already)

2022-09-26 14:57 UTC, godexsoft commented on src/backend/BackendInterface.h
> +/**
All these doxy comments should probably not be part of this pr either. Basically all changes but the limit line should not be in this pr.

2022-09-26 14:57 UTC, godexsoft commented on src/rpc/RPC.cpp
> +    {"noripple_check", &doNoRippleCheck, LimitRange{1, 300, 500}},
This is the only change to leave in this pr. Remove every other change please.

2022-09-26 20:09 UTC, cjcobb23 requested changes
I agree with @godexsoft , this should be a one-line change in a single commit

2022-09-27 03:49 UTC, officialfrancismendoza commented
@godexsoft found a great hotfix. All I have to do is run `git reset --hard origin/develop` to eliminate all the egregious commits and be up-to-date with latest develop commits, make changes to files of interest, and then rebase that way

2022-09-27 14:31 UTC, godexsoft approved these changes, later dismissed
LGTM!

2022-09-27 16:10 UTC, cjcobb23 approved these changes, later dismissed
LGTM

2022-09-27 19:42 UTC, officialfrancismendoza commented
@godexsoft @cjcobb23 I do not have privileges to merge PRs to develop
![image](https://user-images.githubusercontent.com/47958858/192620514-2bd5bf4b-c468-47d1-b586-fbf81781ef06.png)

2022-09-27 23:33 UTC, godexsoft commented
> @godexsoft @cjcobb23 I do not have privileges to merge PRs to develop ![image](https://user-images.githubusercontent.com/47958858/192620514-2bd5bf4b-c468-47d1-b586-fbf81781ef06.png)

Looks like you forgot to sign (gpg) your commit. If unsure - go check CONTRIBUTING.md for details :+1:

2022-09-30 14:59 UTC, cjcobb23 submitted a review, later dismissed
LGTM

2022-10-04 14:03 UTC, cjcobb23 approved these changes

2022-10-04 14:04 UTC, merged