Return noPermission in ledger admin call
XRPLF/clio pull request #360
Opened 2022-10-11 03:26 UTC by officialfrancismendoza

**Issue** (#280): ledger API call does not return an error message at all instead of returning noPermission error message when using admin methods.
**Fix**: Add noPermission error and conditional.

2022-10-26 20:07 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +        if ((params.at(JS(full)).as_bool() &&
I wonder if this will crash if i send a `full` or `accounts` that is not a `bool`?

2022-10-27 14:54 UTC, cjcobb23 commented
We actually don't support these flags at all, admin or not. The ledger is far too big to return in one RPC. Is there any sort of not supported error we can return?

2022-11-14 21:42 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +            return Status{Error::rpcNO_PERMISSION, "noPermission"};
We can use `rpcNOT_SUPPORTED` here or once we merge #396 we will be able to add and return a custom `clio` error for this if desired.

2022-11-14 21:43 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +        if ((params.at(JS(full)).as_bool() &&
I'd say let's remove this inner `if` checks completely (avoiding the crash) and just return `rpcNOT_SUPPORTED` when either `full` or `accounts` is present in the request.

2022-11-16 15:11 UTC, godexsoft commented
> We actually don't support these flags at all, admin or not. The ledger is far too big to return in one RPC. Is there any sort of not supported error we can return?

@officialfrancismendoza as @cjcobb23 suggested above - let's use `rpcNOT_SUPPORTED` in case any of these fields are passed be it a bool or not. This will simplify the fix a lot and we won't be parsing useless flags we aren't using.

2022-11-16 15:14 UTC, godexsoft requested changes
Let's use `rpcNOT_SUPPORTED` - see comment.

2022-11-16 19:12 UTC, godexsoft requested changes

2022-11-16 19:12 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +    if (params.contains(JS(full)) && params.contains(JS(accounts)))
Split this into two separate `if`s each checking its own field. If any of the fields is present (we don't care the type anymore) just return the `rpcNOT_SUPPORTED` code.

2022-11-16 19:12 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +            (params.at(JS(full)).as_bool() &&
Checking for bool is irrelevant if we don't support the field at all.

2022-11-16 19:12 UTC, godexsoft commented on src/rpc/handlers/Ledger.cpp
> +            return Status{RippledError::rpcNOT_SUPPORTED, "notSupported"};
You don't need to pass "notSupported" as second argument - it should auto-fill the message from rippled codebase.

2022-11-17 17:01 UTC, godexsoft approved these changes
Looks like this should do it.

2022-11-17 17:02 UTC, merged