helper function for subscribe to ensure cleanup
XRPLF/clio pull request #402
Opened 2022-11-15 17:49 UTC by cjcobb23

There was a memory leak where some subscriptions were not being cleaned up. This commit fixes that, and makes it easier to ensure this mistake doesn't happen again in the future

2022-11-15 18:22 UTC, godexsoft requested changes
While this approach works.. perhaps this is a good opportunity to rethink the design here?
Why not use a simple wrapper class that holds onto both the `session` and the function to call on removal from the subscribers list.. you can call your lambda in the destructor and have a strong guarantee that it will be called at all times even if we throw an exception somewhere between adding it to the map and registering the cleanup function. I'd try to use a single vector/map here instead of two separate containers. WDYT?

2022-11-15 18:22 UTC, godexsoft commented on src/subscriptions/SubscriptionManager.cpp
> +    cleanupFuncs_[session].emplace_back(func);
Here 'func' is an lvalue within the body of the function (even tho it's passed as &&, it has a name so it's an lvalue) so you are actually copying 'func'. Also `emplace_back` does not actually _emplace_ here so i suggest you do `push_back(std::move(func))` instead.

2022-11-15 19:23 UTC, cjcobb23 commented
> While this approach works.. perhaps this is a good opportunity to rethink the design here?
> Why not use a simple wrapper class that holds onto both the `session` and the function to call on removal from the subscribers list.. you can call your lambda in the destructor and have a strong guarantee that it will be called at all times even if we throw an exception somewhere between adding it to the map and registering the cleanup function. I'd try to use a single vector/map here instead of two separate containers. WDYT?

Should be possible. We'd still need a collection inside the wrapper class to track which cleanup functions to call for that session.

2022-11-17 16:32 UTC, godexsoft commented
> Should be possible. We'd still need a collection inside the wrapper class to track which cleanup functions to call for that session.

Yea, i see. Up to you if you want to refactor it now or we redesign it later.
Please at least still fix the `emplace_back`.

2022-11-17 17:57 UTC, cjcobb23 commented
I think since this is a memory leak, i'd rather get the fix in now and redesign later

2022-11-17 18:41 UTC, godexsoft submitted a review, later dismissed
LGTM.

2022-11-18 16:31 UTC, godexsoft approved these changes
LGTM.

2022-11-22 18:39 UTC, merged