include searched_all in error response of tx
XRPLF/clio pull request #407
Opened 2022-11-17 01:14 UTC by cjcobb23

This PR fixes a couple of bugs. Fixes https://github.com/XRPLF/clio/issues/278. Also performs other checks on the ledger range supplied by the user in order to align with rippled. Also actually implements the `searched_all` functionality: https://xrpl.org/tx.html#not-found-response
Supersedes: https://github.com/XRPLF/clio/pull/359

2022-11-17 15:15 UTC, godexsoft commented on src/rpc/Errors.cpp
> +        for (auto it = status.extraInfo->begin(); it != status.extraInfo->end();
Wouldn't `for(auto const& [key, value] : status.extraInfo)` or something similar work here?

2022-11-17 15:15 UTC, godexsoft commented on src/rpc/handlers/Tx.cpp
> +            return Status{RippledError::rpcTXN_NOT_FOUND, extra};
Not a very expensive copy of `extra` but can be made into a `move` if you `std::move(extra)` and change/add a constructor of `Status` to support move. Depending on how often this is hit it can be important.

2022-11-17 17:51 UTC, cjcobb23 commented on src/rpc/Errors.cpp
> +        for (auto it = status.extraInfo->begin(); it != status.extraInfo->end();
good call, changed

2022-11-17 17:51 UTC, cjcobb23 commented on src/rpc/handlers/Tx.cpp
> +            return Status{RippledError::rpcTXN_NOT_FOUND, extra};
changed the constructor to support move

2022-11-17 18:44 UTC, godexsoft requested changes

2022-11-17 18:44 UTC, godexsoft commented on src/rpc/Errors.h
> +        : code(code), extraInfo(extraInfo){};
I think you still need to `std::move` here as `extraInfo` is an lvalue here too.

2022-11-21 19:12 UTC, godexsoft approved these changes, later dismissed
LGTM.

2022-11-21 21:32 UTC, godexsoft approved these changes

2022-11-21 21:52 UTC, merged