Change returned error to accountNotFound
XRPLF/clio pull request #415
Opened 2022-11-21 19:07 UTC by godexsoft

Fixes #277

2022-11-22 21:48 UTC, cjcobb23 requested changes

2022-11-22 21:48 UTC, cjcobb23 commented on src/rpc/RPCHelpers.cpp
> +    return Status{RippledError::rpcACT_NOT_FOUND};
I don't think we should make this change. The account is malformed, as opposed to well formed but not found. This is the issue we were talking about before, where rippled interprets malformed accounts as just strings and treats them as a seed. Given that we decided to not accept seeds as accounts, I believe we are already returning the right error here, and there is no change that needs to be made to the code as is.

2022-11-23 14:55 UTC, godexsoft commented on src/rpc/RPCHelpers.cpp
> +    return Status{RippledError::rpcACT_NOT_FOUND};
@ManiMounikaKunasani please see above and let me know if you have objections.

2022-11-30 22:02 UTC, godexsoft commented
Was decided not to allow seeds. Closing

2022-11-30 22:02 UTC, closed without merging