Add unittests for subscription
XRPLF/clio pull request #488
Opened 2023-01-26 15:54 UTC by cindyyan317

1 Update subscription , make it to be testable
2 Add test
3 Also add some util functions to create test objects.

2023-01-27 14:03 UTC, cindyyan317 commented on src/subscriptions/SubscriptionManager.cpp
> -template <class T>
These functions are moved to header file to be tested.

2023-01-27 14:05 UTC, cindyyan317 commented on src/subscriptions/SubscriptionManager.cpp
> -        if (!node.isFieldPresent(ripple::sfLedgerEntryType))
line 294 deserializeTxPlusMeta already check this.

2023-01-27 14:09 UTC, cindyyan317 commented on src/subscriptions/SubscriptionManager.cpp
> -    if (bookChangesSubscribers_.empty())
We should not check the subscribers here. The sub method run asynchronously. If a message need to be published just after subscribing, the session will be ignored.

2023-01-31 00:14 UTC, godexsoft requested changes
Great job getting so many tests in!
Let's try to fix some simple issues that i noted. 
Some of them may be harder than others and can be left for next iteration/sprint instead.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    Copyright (c) 2022, the clio developers.
minor - it's 2023 already :) here and everywhere else where this header was added.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +#include <boost/json/parse.hpp>
minor - we try to group and order the includes:
1st group - local files (in this case anything in unittest/*)
2nd group - 3rd party libraries like boost/gmock etc.
3rd group - std stuff like 'chrono'

here and everywhere else your changes affect :)

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> + *  test subscription factory method and report function
anything starting with `/**` ends up in generated documentation (doxygen). i'd avoid documenting unit tests (consider using regular comments instead `/*`)

for brevity i'm not going to repeat this comment for every instance - please fix wherever you added this and you recognize it should not be there 🥇

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +            {
minor - formatting could be nicer here. i'd put `{` and `}` next to the opening and closing parens but it's up to you.

here and everywhere else (all formatting of json seems a bit random).

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    clio::Config cfg{json::parse(R"JSON({})JSON")};
minor - here there is not much point in using `R"JSON( )JSON"` since you are not actually multilining nor using `"` within the JSON. 
other than that, it's possible to use just `R"({ "some" : "json" })"` and the result would be the same.
again, up to you.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    clio::Config cfg{json::parse(R"JSON({})JSON")};
and for default config you could just do `clio::Config cfg;`

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    std::shared_ptr<BackendInterface> mockBackendPtr;
It may be worth extracting `MockBackendFixture` and inherit from it instead. I feel like this is going to be useful in a whole lot of places soon! wdyt? I'd put it with other fixtures we have.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    std::this_thread::sleep_for(20ms);
ideally we should not do anything with threads if that's possible. if it's too much refactoring to support that then let's leave it for now and get back to this later.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    EXPECT_EQ(report["book_changes"], 1);
this block of checks is the same as below and really the same as `ReportReturn`. consider making a helper function/lambda that you give one `int` and it spits out a `json::object` that you can just compare to `report` here with one call.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    MockBackend* rawBackendPtr = (MockBackend*)mockBackendPtr.get();
i bet there is a way to avoid both raw pointer and C-style casting or at least the latter. check `EXPECT_CALL` and `ON_CALL` docs please 🥇 

there is many instances of the same issue in the proposed changes. ideally we should get rid of all of them. 
if raw pointer is unavoidable, let's at least not use c-style casts.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    const uint32_t rangeMin = 10;
consider removing if we are not reusing these constants - can just use the values straight away (10u, 30u), possibly with comment like `// min` and `// max`

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    ripple::LedgerInfo();
what is this? do we need it?
also same thing in a few more places.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +        subManagerPtr->subLedger(yield, session);
oof.. we should really refactor this to get rid of yield in the api of submanager.. but i understand it's a lot of work rn so let's leave it for later :(

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    std::shared_ptr<WsBase> session =
seems like we have a bunch of tests that start like this - consider refactoring into a separate fixture and suite.

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    const uint32_t rangeMin = 10;
same as before

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    auto dummyTransaction =
i liked the constexpr static. consider adding for consistency :)

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionTest.cpp
> +    std::shared_ptr<WsBase> session1(new MockSession(tagDecoratorFactory));
let's use std::make_shared here and all other instances of `new` :)

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionTest.cpp
> +    SubscriptionMap<std::string> subMap(ctx);
consider refactoring to a separate suite, `SubscriptionMapTest`

2023-01-31 00:14 UTC, godexsoft commented on unittests/util/TestObject.h
> +CreateLedgerInfo(const char* ledgerHash, ripple::LedgerIndex seq);
if using `string_view` is an option, we should prefer it over `const char*`. please consider here and everywhere else 👍

2023-01-31 00:14 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    constexpr static auto dummyManifest = R"JSON(
for simple json like this, consider using one liners to save space.

2023-01-31 00:14 UTC, godexsoft commented on unittests/util/MockWsBase.h
> +class MockSession : public WsBase
i guess this can be a struct if everything is to stay public? same below.

2023-01-31 08:55 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +#include <boost/json/parse.hpp>
i think it is done automatically in my vs code~ i will try to switch it off

2023-01-31 09:05 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +#include <boost/json/parse.hpp>
we have "SortIncludes:    true" cfg in our clang-format setting. let us turn it off in other PR

2023-01-31 09:36 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +    std::this_thread::sleep_for(20ms);
yea, my plan is getting it tested first, then remove this part.

2023-01-31 09:58 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +    const uint32_t rangeMin = 10;
use rangeMin, rangeMax is more expressive to set the range. the API we call is the same one "updaterange"

2023-01-31 10:00 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +    ripple::LedgerInfo();
forgot to delete it :(

2023-01-31 10:02 UTC, cindyyan317 commented on unittests/SubscriptionManagerTest.cpp
> +    MockBackend* rawBackendPtr = (MockBackend*)mockBackendPtr.get();
no , expect_call and on_call receive obj http://google.github.io/googletest/reference/mocking.html

2023-02-01 23:11 UTC, godexsoft reviewed
Found just a few minor things that you missed i think. LGTM in general :)

2023-02-01 23:11 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +    })";
minor: this tab could be removed

2023-02-01 23:11 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> + * */
minor: looks like a different format of comments to what we use normally (compared to your other comments in this file)

2023-02-01 23:11 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> +/**
minor: still a doxygen comment here

2023-02-01 23:11 UTC, godexsoft commented on unittests/SubscriptionManagerTest.cpp
> + * */
minor: strange comment format again

2023-02-02 16:28 UTC, godexsoft approved these changes, later dismissed
LGTM! 🚀

2023-02-02 16:38 UTC, godexsoft approved these changes

2023-02-03 09:07 UTC, merged