Ledger entry in new RPC framework
XRPLF/clio pull request #534
Opened 2023-03-07 12:57 UTC by cindyyan317

1 Add currency validator 
2 Change ledger hash validator to uint256 validator which can be used for other fields
3 Add AccountBase58Validator for validate base58 account (not include public key)
4 Add test utility functions to generate ledger entries 
5 Add unittests

2023-03-13 13:00 UTC, godexsoft requested changes
Some important design questions to review. Other than that it's pretty good!

2023-03-13 13:00 UTC, godexsoft commented on src/rpc/ngHandlers/LedgerEntry.h
> +        std::optional<boost::json::object> directory;
Is there a way to not leak `json::object` into rpc handler input here? Ideally we want Input to be free from json completely.

2023-03-13 13:00 UTC, godexsoft commented on src/rpc/ngHandlers/LedgerEntry.cpp
> +    if (input.index)
Maybe this whole thing should be in `tag_invoke` instead? And Input should have a `std::variant` for fields that can be represented in different ways.

2023-03-14 09:04 UTC, cindyyan317 commented on src/rpc/ngHandlers/LedgerEntry.h
> +        std::optional<boost::json::object> directory;
If we don't use json object here, we will need to create strong type for all the request types, "directory" ,"offer", "escrow" etc. Even we take effort to prepare all the type, for "directory",  we have some check like only one of "owner" and "dir_root" can be available. Current validators can not support this, we can not do it in tag_invoke either.

2023-03-14 09:06 UTC, cindyyan317 commented on src/rpc/ngHandlers/LedgerEntry.cpp
> +    if (input.index)
you mean we calculate the key index in tag_invoke?

2023-03-14 13:58 UTC, godexsoft commented on src/rpc/ngHandlers/LedgerEntry.h
> +        std::optional<boost::json::object> directory;
I see. Let's add a `TODO: extract to custom types and remove json usage from Input struct` and move on for now.

2023-03-14 14:19 UTC, godexsoft requested changes
Few minor comments added, nothing major 🚀

2023-03-14 14:19 UTC, godexsoft commented on src/rpc/ngHandlers/LedgerEntry.cpp
> +    const ripple::STLedgerEntry sle{
West const detected 😃

2023-03-14 14:19 UTC, godexsoft commented on src/rpc/ngHandlers/LedgerEntry.cpp
> +    if (indexFieldType != indexFieldTypeMap.end())
minor: I think this whole sheet of `if`s can be made into `if-elseif` with just one `return input` at the very bottom of the function. wdyt?

2023-03-15 12:22 UTC, godexsoft approved these changes
LGTM! 🚀

2023-03-15 13:01 UTC, merged