Transaction entry with new RPC framework
XRPLF/clio pull request #553
Opened 2023-03-23 14:27 UTC by cindyyan317

2023-03-23 17:55 UTC, godexsoft requested changes
Left a couple of comments. All looks good overall! 💪

2023-03-23 17:55 UTC, godexsoft commented on src/rpc/ngHandlers/TransactionEntry.cpp
> +    output.tx = std::move(txn);
I think these "moves" may not "move" because of the `const` in `auto const [txn, meta]` above.

2023-03-23 17:55 UTC, godexsoft commented on unittests/rpc/handlers/TransactionEntryTest.cpp
> +    runSpawn([this](boost::asio::yield_context yield) {
minor: This can be `auto& yield` for less typing and less copying (probably very cheap eitherway).

2023-03-24 08:55 UTC, cindyyan317 commented on src/rpc/ngHandlers/TransactionEntry.cpp
> +    output.tx = std::move(txn);
ha. nice to know this

2023-03-24 12:01 UTC, godexsoft approved these changes
LGTM 🚀

2023-03-24 12:57 UTC, merged