account_info implementation in new RPC framework
XRPLF/clio pull request #573
Opened 2023-03-31 08:45 UTC by cindyyan317

2023-03-31 17:53 UTC, godexsoft requested changes
Adding a few small suggestions. Overall looks great as always ⭐

2023-03-31 17:53 UTC, godexsoft commented on src/rpc/ngHandlers/AccountInfo.cpp
> +                RPC::toJson(signerList));
Let's add a todo for later here to 
- replace `toJson` with `tag_invoke`
- not look up `signer_lists` + `as_array` each iteration
This really should be just `jv.as_object().insert_or_assign(JS(signer_lists)), output.signerLists);` if all `tag_invoke`s are correctly added.

2023-03-31 17:53 UTC, godexsoft commented on src/rpc/ngHandlers/AccountInfo.h
> +    // TODO: ident is not in document
Consider adding an issue for the doc update and posting a link to it here in this todo 🙇

2023-03-31 17:53 UTC, godexsoft commented on src/rpc/ngHandlers/AccountInfo.h
> +        static const RpcSpec rpcSpec = {
`static auto const rpcSpec = RpcSpec{` is nicer and and also puts `const` in the usual spot 👍

2023-03-31 17:53 UTC, godexsoft commented on unittests/rpc/handlers/AccountInfoTest.cpp
> +// constexpr static auto INDEX2 =
Can remove these commented out lines :)

2023-04-03 08:47 UTC, cindyyan317 commented on src/rpc/ngHandlers/AccountInfo.cpp
> +                RPC::toJson(signerList));
I think we have to postpone this change. 
Currently we have SLE tag_invoke here -> https://github.com/XRPLF/clio/blob/232acaeff293a43f97d332eb196263930ddedeac/src/rpc/ngHandlers/NFTOffersCommon.cpp#L33

If we put this function in a common place, convert SLE to json value according to the SLE type, it will work, but not ideal. 
because we need more information to distinguish the ledger detail,
for example, current https://github.com/XRPLF/clio/blob/232acaeff293a43f97d332eb196263930ddedeac/src/rpc/ngHandlers/NFTOffersCommon.cpp#L33 is only for nft offer not general offer.

2023-04-03 10:01 UTC, godexsoft commented on src/rpc/ngHandlers/AccountInfo.cpp
> +                RPC::toJson(signerList));
I'm ok with that. Just add a TODO comment about this desired change then and let's move on :)

2023-04-03 15:05 UTC, godexsoft approved these changes
LGTM 🚀

2023-04-03 16:03 UTC, merged