account_objects of new RPC framework
XRPLF/clio pull request #599
Opened 2023-04-21 13:18 UTC by cindyyan317

2023-04-24 12:06 UTC, godexsoft requested changes
Adding a few small suggestions - overall looking good!

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.cpp
> +    {
Could remove the extra braces

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.cpp
> +    }
And add a space after the for loop

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.cpp
> +        {JS(account_objects), objects}};
Line of space would be nice before the if

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.cpp
> +    input.account = jv.at(JS(account)).as_string().c_str();
I often ignore these small things but really we should put more spacing before/after `if`, `for` etc.

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.h
> +                 "state",
There are no JS() for any of these?

2023-04-24 12:06 UTC, godexsoft commented on src/rpc/ngHandlers/AccountObjects.h
> +    static std::unordered_map<std::string, ripple::LedgerEntryType> const TYPESMAP;
This would probably be better placed at the top private section, next to other 'data'

2023-04-24 13:25 UTC, cindyyan317 commented on src/rpc/ngHandlers/AccountObjects.h
> +                 "state",
No~ unfortunately

2023-04-25 08:08 UTC, godexsoft approved these changes
LGTM!

2023-04-25 08:14 UTC, merged