Nftids
XRPLF/clio pull request #780
Opened 2023-07-19 16:40 UTC by cindyyan317

2023-07-24 11:57 UTC, cindyyan317 commented on src/rpc/RPCHelpers.cpp
> +std::optional<ripple::uint256>
The helper functions are mainly from https://github.com/XRPLF/rippled/blob/develop/src/ripple/rpc/NFTokenID.h which is not in libxrpl's scope.

2023-07-24 11:58 UTC, cindyyan317 commented on src/rpc/RPCHelpers.cpp
> +toExpandedJson(Backend::TransactionAndMetadata const& blobs, NFTokenJSON NFTEnabled)
This function is called by other handlers, only tx and account_tx can append nftid

2023-07-26 15:01 UTC, godexsoft requested changes
Leaving a few suggestions, mostly small formatting and styling issues - the code changes look good to me.

2023-07-26 15:01 UTC, godexsoft commented on src/rpc/RPCHelpers.cpp
> +toExpandedJson(Backend::TransactionAndMetadata const& blobs, NFTokenJSON NFTEnabled)
Can we have the parameter `NFTEnabled` be lowercased please? It looks like a `Type` this way.. 
Maybe `nftEnabled` is better? 👍

2023-07-26 15:01 UTC, godexsoft commented on unittests/rpc/handlers/AccountTxTest.cpp
> +                "account":"{}",
Space missing 🥇

2023-07-26 15:01 UTC, godexsoft commented on unittests/rpc/handlers/AccountTxTest.cpp
> +                "marker": {{"ledger":10,"seq":11}}
Spaces missing

2023-07-26 15:01 UTC, godexsoft commented on unittests/rpc/handlers/AccountTxTest.cpp
> +static std::vector<TransactionAndMetadata>
If this is only used in this cpp unit, let's make it a regular function in an unnamed namespace at the top (see other examples in the codebase - search for `namespace {`).

2023-07-26 15:01 UTC, godexsoft commented on src/rpc/RPCHelpers.h
> +enum class NFTokenJSON { Enable, Disable };
Other `enum class`es in Clio all use CAPITALized names for their values. Let's try to stick with that 👍

2023-07-26 15:33 UTC, godexsoft approved these changes
👍

2023-07-26 16:12 UTC, merged