Move AdminVerificationStrategy to Server
XRPLF/clio pull request #965
Opened 2023-11-01 09:13 UTC by cindyyan317

Following this PR #958 
This PR removes the password member from Server class. Also AdminVerificationStrategy can be shared between sessions. This PR move the construction from session to web server.

2023-11-01 12:14 UTC, kuznetsss requested changes

2023-11-01 12:14 UTC, kuznetsss commented on src/web/impl/HttpBase.h
> +        std::shared_ptr<AdminVerificationStrategy> const& adminVerification,
Better to take by copy and move it (will remove one reference creation)

2023-11-01 12:15 UTC, kuznetsss commented on src/web/SslHttpSession.h
> +        std::shared_ptr<detail::AdminVerificationStrategy> const& adminVerification,
Here also better to copy and move

2023-11-01 14:57 UTC, cindyyan317 commented on src/web/SslHttpSession.h
> +        std::shared_ptr<detail::AdminVerificationStrategy> const& adminVerification,
I hesitate to change this one, because there is no copy construction happening inside this function. I think it is okay to pass const& here, instead of move it while call other function.

2023-11-02 10:04 UTC, kuznetsss approved these changes

2023-11-02 10:17 UTC, merged